project:
  type: book
  output-dir: docs

book:
  title: "Analyse"
  author: "Guillaume Gilles"
  date: "1/26/2026"
  navbar:
    right:
      - href: https://guillaumegilles.github.io/about.html
        text: "About"
      - href: https://guillaumegilles.github.io/
        text: "Projects"
      - href: https://guillaumegilles.github.io/teaching.html
        text: "Teaching"
  chapters:
    - index.qmd
    - 01-temple-bilans.qmd
    - 02-archives-consolidees.qmd
    - 03-detective-diagnostic.qmd
    - references.qmd
  appendices:
    - banque-france.qmd
    - banque-france-cotation.qmd

bibliography: references.bib

format:
  html:
    light: light.scss

